feat: show backup UI
internxt/drive-desktop-macos pull request #42
Opened 2024-02-27 18:13 UTC by rascanio97

2024-02-28 08:48 UTC, PixoDev requested changes
Looking good, we may need to start thinking into adding tests to the project more consistently, as we are reliying a lot now in manual testing, and that doesn't scalate well

2024-02-28 08:48 UTC, PixoDev commented on InternxtDesktop/Views/Backup/DeviceCardComponent.swift
> +                    .progressViewStyle(LinearProgressViewStyle(tint: .blue))
Replace this `ProgressView` by an undeterminated ProgressView for now, see below GIF. Also use the proper color, I bet is not `.blue`, that's a system one

https://gyazo.com/a8c78bb61487370615edf792b7202fdb

2024-02-28 08:48 UTC, PixoDev commented on Shared/Services/BackupsService.swift
> +            await MainActor.run { [weak self] in
what's this for?

2024-02-28 08:48 UTC, PixoDev commented on Shared/Services/BackupsService.swift
> +                let _ = try await self.getDeviceChilds(deviceId: deviceId)
try to not introduce new concepts, a "device child" is a backup folder I believe, use proper names so we speak the same language and we understand each other

2024-02-28 08:48 UTC, PixoDev commented on Shared/Services/BackupsService.swift
> +        DispatchQueue.main.async { [weak self] in
Why we need to do this here? Why can't we do this:

```
 DispatchQueue.main.async {
     self.propagateSuccess()
 }
```

So the propagateSuccess method is thread independent

2024-02-28 08:48 UTC, PixoDev commented on XPCBackupService/Entities/BackupTreeNode.swift
> +    func syncNodes(progress: Progress) async throws -> Void {
Pass the progress to the BackupTreeNode via initializator, so you can sync a node without a progress if needed

2024-02-28 08:48 UTC, PixoDev commented on XPCBackupService/Entities/BackupTreeNode.swift
> +    private func syncNode(progress: Progress) async throws -> Void {
quick tip, you don't need named parameters all the time, this works better for methods that only allows one argument:

`private func syncNode(_ progress: Progress) async throws -> Void`

And you can call this like this:
`syncNode(progress)`

In any case, remove the progress parameter here, send it to the BackupTreeNode via initializator

2024-02-28 08:48 UTC, PixoDev commented on XPCBackupService/XPCBackupService.swift
> +
Can you log the progress here to see if it's working as expected?

2024-02-28 14:05 UTC, rascanio97 commented on InternxtDesktop/Views/Backup/DeviceCardComponent.swift
> +                    .progressViewStyle(LinearProgressViewStyle(tint: .blue))
this is exactly the component i added here lol. i can change the color tho. thanks!

2024-02-28 14:07 UTC, rascanio97 commented on Shared/Services/BackupsService.swift
> +            await MainActor.run { [weak self] in
bc it's raising a warning saying that we can't update a Published variable on a background thread. it needs to be in main thread and this is a way to do that in an `async` function. replacing the `DispatchQueue.main.async {}`

2024-02-28 14:07 UTC, rascanio97 commented on Shared/Services/BackupsService.swift
> +        DispatchQueue.main.async { [weak self] in
can't do this in the XPCService function callback. it throws an error

2024-02-28 18:52 UTC, rascanio97 commented on XPCBackupService/Entities/BackupTreeNode.swift
> +    func syncNodes(progress: Progress) async throws -> Void {
if i do this i will have a progress for each node, i want a progress for all nodes, and all trees.

2024-02-29 14:02 UTC, PixoDev commented on XPCBackupService/Entities/BackupTreeNode.swift
> +    func syncNodes(progress: Progress) async throws -> Void {
You can still have a progress for each node, I believe that the progress you are sending here is the `backupProgress` in any case, you can send down the `backupProgress` here when generating the `BackupTreeNode`

https://github.com/internxt/drive-desktop-macos/blob/main/XPCBackupService/Services/BackupTreeGenerator.swift#L107

2024-02-29 17:32 UTC, PixoDev approved these changes

2024-02-29 18:50 UTC, merged